[package]
name = "day-9"
version = "0.1.0"
authors = ["Kenny Baskett <kbaskett248@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = { path = "../mylib" }
