[package]
name = "day-10"
version = "0.1.0"
authors = ["Kenneth Baskett <kbaskett248@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mylib = { path = "../mylib" }